import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.mpp.NativeBuildType

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

// Facts the build knows and the code should not have to be told twice: the version, and
// where the server is. Both were literals — the version went stale three milestones running,
// and the server URL was hardcoded to localhost, which no phone can reach.
val generateBuildInfo by tasks.registering {
    val output = layout.buildDirectory.dir("generated/buildinfo")
    val versionOf = project.version.toString()
    val serverUrl =
        providers.gradleProperty("yellowtrack.serverUrl").orNull
            // Only reached if gradle.properties has been emptied; the declared default is
            // the deployed server, because a build made without thinking about this should
            // reach the studio's data rather than a port on the machine that compiled it.
            ?: error("yellowtrack.serverUrl is not set; see gradle.properties")

    inputs.property("version", versionOf)
    inputs.property("serverUrl", serverUrl)
    outputs.dir(output)

    doLast {
        val target = output.get().asFile.resolve("com/yellowtrack/platform/app")
        target.mkdirs()
        target.resolve("BuildInfo.kt").writeText(
            """
            package com.yellowtrack.platform.app

            /**
             * Generated by the `generateBuildInfo` Gradle task. Do not edit.
             *
             * The server comes from `yellowtrack.serverUrl`, declared in `gradle.properties`
             * and overridable per build:
             *
             *     ./gradlew :desktopApp:run -Pyellowtrack.serverUrl=http://localhost:8080
             *
             * It used to default to loopback, which meant every build anyone made without
             * remembering the flag pointed at a port on the machine that compiled it — and
             * on a phone, `localhost` is the phone.
             */
            object BuildInfo {
                const val VERSION: String = "$versionOf"
                const val SERVER_URL: String = "$serverUrl"
            }
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    // Release frameworks are linked with full LLVM optimisation, which on a three-core CI
    // runner takes three quarters of an hour for one architecture and barely parallelises.
    // Nothing on CI consumes them: Xcode links its own through
    // `embedAndSignAppleFrameworkForXcode`, and no artefact is published. So CI opts out
    // with -Pyellowtrack.iosReleaseFrameworks=false while every other build — including an
    // archive from Xcode — keeps both build types and is unaffected.
    val appleTargetsSupported =
        providers.gradleProperty("yellowtrack.appleTargets").orNull?.toBooleanStrictOrNull()
            ?: System.getProperty("os.name").orEmpty().startsWith("Mac")

    val iosBuildTypes =
        if (providers.gradleProperty("yellowtrack.iosReleaseFrameworks").orNull == "false") {
            listOf(NativeBuildType.DEBUG)
        } else {
            listOf(NativeBuildType.DEBUG, NativeBuildType.RELEASE)
        }

    // Declared only on a Mac; see the note in the `yellowtrack.kmp.library` convention.
    if (appleTargetsSupported) {
        listOf(
            iosArm64(),
            iosSimulatorArm64(),
        ).forEach { iosTarget ->
            iosTarget.binaries.framework(iosBuildTypes) {
                baseName = "Shared"
                isStatic = true
            }
        }
    }

    jvm()

    android {
        namespace = "com.yellowtrack.platform.app"
        compileSdk =
            libs.versions.android.compileSdk
                .get()
                .toInt()
        minSdk =
            libs.versions.android.minSdk
                .get()
                .toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        androidResources {
            enable = true
        }
        withHostTest {
            isIncludeAndroidResources = true
        }
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }.configure {
            instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        }
    }

    // ...
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.compose.uiTooling)
            implementation(libs.koin.android)
        }
        commonMain {
            kotlin.srcDir(generateBuildInfo)
        }

        commonMain.dependencies {
            implementation(project(":shared:core:designsystem"))
            implementation(project(":shared:core:model"))
            implementation(project(":shared:core:common"))
            implementation(project(":shared:core:data"))
            implementation(project(":shared:core:database"))
            implementation(project(":shared:core:export"))
            implementation(project(":shared:core:navigation"))

            implementation(project(":shared:core:network"))
            implementation(project(":shared:feature:auth"))
            implementation(project(":shared:feature:dashboard"))
            implementation(project(":shared:feature:clients"))
            implementation(project(":shared:feature:ledger"))
            implementation(project(":shared:feature:sessions"))
            implementation(project(":shared:feature:studio"))
            implementation(project(":shared:feature:settings"))

            implementation(libs.compose.materialIconsExtended)
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.koin.core)
            // Add only when shared Compose code injects dependencies directly.
            implementation(libs.koin.compose)
            implementation(libs.koin.coreViewmodel)
            implementation(libs.koin.composeViewmodel)
            implementation(libs.kotlinx.coroutines.core)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }

        // Skiko's native binary, so a JVM test can rasterise a screen to a PNG without
        // opening a window. The feature modules get this from the shared compose convention
        // plugin; this module does not use it, which is why the sidebar — the one screen
        // that lives here — had never been rendered and its landscape clipping went unseen.
        // Test-only; it ships with no target.
        jvmTest.dependencies {
            implementation(compose.desktop.currentOs)
        }

        /*wasmJsMain.dependencies {
            // Wasm-specific dependencies

           // wasmJsMain.dependencies {
                implementation(":shared")

                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.ui)
           // }
        }*/
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}
